# -*- coding: utf-8 -*-
"""Airbnb data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wDBCSoTYfFrqsrlnPjSgr3TDqDEB9ac
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Airbnb dataset
airbnb_data = pd.read_csv('Airbnb data.csv')

# Display the first few rows of the dataset
airbnb_data.head()
# Get basic information about the dataset
airbnb_data.info()
# Summary statistics
airbnb_data.describe()

# Example: Histogram of property prices
plt.figure(figsize=(10, 6))
sns.histplot(airbnb_data['price'], bins=30, kde=True)
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Distribution of Property Prices')
plt.show()

# Create a correlation matrix
corr_matrix = airbnb_data.corr()

# Create a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Airbnb Data')
plt.show()